version: '3.8'

services:
  redis:
    build: ./redis
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - CLOVA_DOMAIN_CODE=${CLOVA_DOMAIN_CODE}
      - CLOVA_DOMAIN_ID=${CLOVA_DOMAIN_ID}
      - CLOVA_SECRET_KEY=${CLOVA_SECRET_KEY}
      - GMS_API_KEY=${GMS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - DB_IP=${DB_IP}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
    depends_on:
      - redis
    expose:
      - "8088"
    networks:
      - app-network

  frontend:
    build: ./frontend
    expose:
      - "3030"
    environment:
      - PORT=3030
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge