version: '3.8'

services:
  backend:
    image: hj00b/recode-backend:staging-${BUILD_NUMBER:-latest}
    container_name: recode-backend-staging
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: hj00b/recode-frontend:staging-${BUILD_NUMBER:-latest}
    container_name: recode-frontend-staging
    expose:
      - "3030"
    environment:
      - NODE_ENV=staging
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: hj00b/recode-nginx:staging-${BUILD_NUMBER:-latest}
    container_name: recode-nginx-staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 