version: '3.8'

services:
  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    expose:
      - "8088"
    networks:
      - app-network

  frontend:
    build: ./frontend
    expose:
      - "3030"
    environment:
      - PORT=3030
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge