version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8088:8088"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3030:3030"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl_certs:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ssl_certs:
