version: '3.8'

services:
  redis:
    build: ./redis
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 30s

  backend:
    build: ./backend
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - CLOVA_DOMAIN_CODE=${CLOVA_DOMAIN_CODE}
      - CLOVA_DOMAIN_ID=${CLOVA_DOMAIN_ID}
      - CLOVA_SECRET_KEY=${CLOVA_SECRET_KEY}
      - GMS_API_KEY=${GMS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - DB_IP=${DB_IP}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
    depends_on:
      - redis
    expose:
      - "8088"
    restart: unless-stopped
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:8088/actuator/health"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - PORT=3030
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - GOOGLE_TTS_API_KEY=${GOOGLE_TTS_API_KEY}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_KAKAO_REDIRECT_URI=${NEXT_PUBLIC_KAKAO_REDIRECT_URI}
    networks:
      - app-network
    restart: always
    depends_on:
      - backend
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s

  prometheus:
    user: "65534:65534"
    build: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.retention.size=5GB
      - --web.enable-lifecycle
      - --web.enable-admin-api
    restart: unless-stopped
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/healthy"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s

  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_SERVER_ROOT_URL=https://recode-my-life.site/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=recode-my-life.site
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=lax
      - GF_SERVER_ENABLE_GZIP=true
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
      - prometheus
      - grafana
    restart: unless-stopped
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "nginx", "-t"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s
    # 기존 서비스들 유지하고 아래 내용 추가

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx:9113/stub_status
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - app-network

  redis-exporter:
    image: oliver006/redis_exporter:v1.55.0
    container_name: redis-exporter
    command:
      - --redis.addr=redis://redis:6379
      - --redis.password=${REDIS_PASSWORD}
    ports:
      - "9121:9121"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.15.0
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=${DATA_SOURCE_NAME}
    ports:
      - "9104:9104"
    restart: unless-stopped
    networks:
      app-network:
        aliases:
          - mysqld-exporter

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - "9100:9100"
    networks:
      - app-network
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  app-network:
    driver: bridge
    name: app-network
