version: '3.8'

services:
  backend:
    image: hj00b/recode-backend:prod-${BUILD_NUMBER:-latest}
    container_name: recode-backend-prod
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: hj00b/recode-frontend:prod-${BUILD_NUMBER:-latest}
    container_name: recode-frontend-prod
    expose:
      - "3030"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: hj00b/recode-nginx:prod-${BUILD_NUMBER:-latest}
    container_name: recode-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge 